FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y git
#RUN apt-get install -y build-essential
#RUN apt-get install -y crossbuild-essential-powerpc
RUN apt-get install -y crossbuild-essential-arm64

ADD compile_arm.sh .
#RUN mkdir /src
#git archive --remote ${GIT_REPO} ${BRANCH} targets/ocotea  | tar xv  -C ${LOCAL_WS}

