FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y build-essential
#RUN apt-get install -y build-essential-powerpc
#RUN apt-get install -y build-arm64


CMD git clone git://mygit/test.git
