FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive
ARG dir=/

RUN apt-get update && apt-get install -y \
    python \
    telnet

WORKDIR ${dir}

ENTRYPOINT ["/usr/bin/python"]
CMD ["-m", "SimpleHTTPServer", "8080"]
